### ISSUE TITLE
lazyYT requires double tap to play videos on iPhone

### ISSUE THREAD

**Issue by adam-s** [tylerpearson/lazyYT#24] opened 2015-03-26 04:52 UTC
When I viewed the demo on my iPhone I clicked the image and it loaded the player. Then I had to click the player to get it to play. It wasn't very intuitive because my first thought was that it was broken on the iPhone. Is it possible to have a single tap to load the player and start the video?

**Comment by tylerpearson** [comment] 2015-03-26 17:07
Hey Adam, this is actually a duplicate of https://github.com/tylerpearson/lazyYT/issues/22. iOS and Android won't autoplay videos.

**Closed by tylerpearson** 2015-03-26 17:07 UTC

**Comment by adam-s** [comment] 2015-03-26 17:39
Sorry, I didn't realize GitHub doesn't show closed issues on default. Compared to infinite scroll and lazy loading videos which I also experimented with this is the lightest and cleanest solution. Thanks for the plugin.
